name: "Terraform Valida Modulo"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    uses: "williamsanmartin4/cicd_centralizado/.github/workflows/terraform_valida_modulo.yaml@feat/terraform-format"
    secrets:
      token: ${{ secrets.TOKEN }}

